### ISSUE TITLE
DxWnd Config

### ISSUE THREAD

**Issue by tuancuong92** [jglim/gunbound-launcher#2]
I tried to run with DxWnd but nothing happened, still full screen and colors issue after Alt-Tab. Can you tell me how to config?

**Comment by jglim** [comment]
This is my DxWnd configuration export that runs fine on unpacked clients (Windows 7)

[SoftnyxGunboundGIS.zip](https://github.com/jglim/gunbound-launcher/files/3243326/SoftnyxGunboundGIS.zip)
