### ISSUE TITLE
How to bypass GameGuard

### ISSUE THREAD

**Issue by darioodiaz** [jglim/gunbound-launcher#3]
Hi, first at all I love you project, thanks you so much.
I have a question, how I can bypass game guard for newer versiones of gunbonund?

**Comment by jglim** [comment]
Every GameGuard implementation will intentionally have some variations, so there isn't a straightforward answer (especially so for the newer versions which I do not work on). For the Thor's Hammer versions that I looked at, I have already documented it [in the server repository](https://github.com/jglim/gunbound-server/#disabling-gameguard).
